### ISSUE TITLE
Get additional information about product (jumbo)

### ISSUE THREAD

**Issue by ItsMeRomian** [bartmachielsen/SupermarktConnector#10]
Hello,

On the official jumbo site and app there is a product description and nutrition information. With the API there is no way to get this information. Is it possible to get this information? 
Screenshot as example:
![image](https://user-images.githubusercontent.com/13468715/98997243-7bc57f80-2534-11eb-8edb-d7815c6c1fde.png)

**Comment by gisteren** [comment]
@ItsMeRomian 

The data is in the API. With the following code, you get the info:

from pprint import pprint
from supermarktconnector.jumbo import JumboConnector
jumboconnector = JumboConnector()
pprint(jumboconnector.get_product_details(product="80349BLK"))

Under the nutritionalData you will find the information:

{
    "product": {
        "data": {
            "id": "80349BLK",
            "title": "Red Bull Energy Drink Regular 250 ml gekoeld",
            "quantityOptions": [
                {
                    "defaultAmount": 1,
                    "minimumAmount": 1,
                    "amountStep": 1,
                    "unit": "pieces",
                    "maximumAmount": 99
                }
            ],
            "prices": {
                "price": {
                    "currency": "EUR",
                    "amount": 165
                },
                "unitPrice": {
                    "unit": "l",
                    "price": {
                        "currency": "EUR",
                        "amount": 660
                    }
                }
            },
            "available": true,
            "productType": "Product",
            "crossSellSKUList": [],
            "quantity": "250 ml",
            "imageInfo": {
                "primaryView": [
                    {
                        "url": "https://static-images.jumbo.com/product_images/250920200808_80349BLK-1_180x180.png",
                        "width": 180,
                        "height": 180
                    },
                    {
                        "url": "https://static-images.jumbo.com/product_images/250920200808_80349BLK-1_720x720.png",
                        "width": 720,
                        "height": 720
                    },
                    {
                        "url": "https://static-images.jumbo.com/product_images/250920200808_80349BLK-1_360x360.png",
                        "width": 360,
                        "height": 360
                    }
                ],
                "details": [
                    {
                        "url": "https://static-images.jumbo.com/product_images/210220190119_80349BLK-5_720x720.png",
                        "width": 720,
                        "height": 720
                    },
                    {
                        "url": "https://static-images.jumbo.com/product_images/210220190119_80349BLK-5_360x360.png",
                        "width": 360,
                        "height": 360
                    }
                ]
            },
            "topLevelCategory": "Fris, sap, koffie, thee",
            "topLevelCategoryId": "SG10",
            "nixProduct": false,
            "hasRelatedProducts": true,
            "nutritionalInformation": [
                {
                    "productTitle": "Red Bull Energy Drink Regular 250 ml gekoeld",
                    "nutritionalGuidelines": {
                        "entries": []
                    },
                    "nutritionalData": {
                        "entries": [
                            {
                                "name": "energie",
                                "valuePer100g": "194 kJ (46 kcal)",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "vetten",
                                "valuePer100g": "0 g",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "waarvan verzadigde vetzuren",
                                "valuePer100g": "0 g",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "koolhydraten",
                                "valuePer100g": "11 g",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "waarvan suikers",
                                "valuePer100g": "11 g",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "eiwitten",
                                "valuePer100g": "0 g",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "zout",
                                "valuePer100g": "0.1 g",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "vitaminen:",
                                "valuePer100g": "",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "niacine",
                                "valuePer100g": "6.4 mg /40% NRV",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "pantotheenzuur",
                                "valuePer100g": "2 mg /33% NRV",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "riboflavine",
                                "valuePer100g": "0.21 mg /15% NRV",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "vitamine B6",
                                "valuePer100g": "0.2 mg /14% NRV",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "vitamine B12",
                                "valuePer100g": "0.4 µg /16% NRV",
                                "valuePerPortion": ""
                            },
                            {
                                "name": "NRV = Voedingswaardereferenties",
                                "valuePer100g": "",
                                "valuePerPortion": ""
                            }
                        ]
                    }
                }
            ],
            "detailsText": "* Red Bull Energy Drink wordt gemaakt van ingrediënten met de hoogste kwaliteit: Alpenwater, suiker, taurine (0,4%), cafeïne (0,03%) en vitamine B\n* Een blikje Red Bull Energy Drink 250 ml bevat 80 mg cafeïne. Dat is ongeveer gelijk aan een kopje koffie\n* De hoeveelheid suiker in Red Bull Energy Drink is vergelijkbaar met appel- of sinaasappelsap: 11g/100ML\n* Vitamine B6 en niacine dragen bij aan vermindering van vermoeidheid en zorgen voor een normale stofwisseling",
            "regulatedTitle": "Energy Drink - hoog cafeïnegehalte. Gepasteuriseerd.",
            "ingredientInfo": [
                {
                    "productTitle": "Red Bull Energy Drink Regular 250 ml gekoeld",
                    "ingredients": [
                        {
                            "name": "Koolzuurhoudend water",
                            "containsAllergens": false
                        },
                        {
                            "name": "sacharose",
                            "containsAllergens": false
                        },
                        {
                            "name": "glucose",
                            "containsAllergens": false
                        },
                        {
                            "name": "voedingszuur (citroenzuur)",
                            "containsAllergens": false
                        },
                        {
                            "name": "taurine (0,4%)",
                            "containsAllergens": false
                        },
                        {
                            "name": "zuurteregelaar (natriumcarbonaten, magnesiumcarbonaat)",
                            "containsAllergens": false
                        },
                        {
                            "name": "cafeïne (0,03%)",
                            "containsAllergens": false
                        },
                        {
                            "name": "vitaminen",
                            "containsAllergens": false
                        },
                        {
                            "name": "aroma's",
                            "containsAllergens": false
                        },
                        {
                            "name": "kleurstof (karamel)",
                            "containsAllergens": false
                        }
                    ]
                }
            ],
            "usageAndSafetyInfo": {
                "storageType": "Ten minste houdbaar tot einde: zie bodem.",
                "recyclingInfo": "Blik: Recyclebaar"
            },
            "additiveInfo": {
                "thirdparty": "Recyclable ALUMINIUM - alu"
            },
            "brandInfo": {
                "brandDescription": "Red Bull Energy Drink is speciaal ontwikkeld voor momenten waarop je meer wilt presteren.",
                "manufacturerAddress": "Red Bull Nederland B.V., Postbus 37711,\n1030 BG Amsterdam.\nwww.redbull.nl",
                "webAddress": "www.redbull.nl"
            }
        }
    }
}

**Comment by ItsMeRomian** [comment]
Sorry, I didn't scroll down so far 😄
