### ISSUE TITLE
product detail URL seems to 404

### ISSUE THREAD

**Issue by ygrange** [bartmachielsen/SupermarktConnector#13]
Looks like the detail URL gives me a 404: https://ms.ah.nl/mobile-services/product/detail/v3/fir/162826 should give some details on Kellog's Cornflakes (don't ask why I test with that :D ) but it gives a 404.

**Comment by bartmachielsen** [comment]
Thanks @casperboone for the fix, I have just released version 0.7 which includes the fix for this
