### ISSUE TITLE
AH: 503 Server Error...

### ISSUE THREAD

**Issue by IpPsar01** [bartmachielsen/SupermarktConnector#15]
Hi,
When making calls to AH I now get: 503 Server Error: Service Unavailable for url: https://ms.ah.nl/create-anonymous-member-token?client=appie-anonymous

Do others experience this also? 
The server it self is reachable via ping. 
Does anyone have a solution for this? 

Thanks in advance!

**Comment by sander102907** [comment]
I have the same issue, it's unfortunate. Hopefully, it's temporary..

**Comment by kirikorneev** [comment]
The same here. Still getting this error. 
@bartmachielsen anything you can do?

**Comment by bartmachielsen** [comment]
Hi @sander102907  and @kirikorneev. Albert Heijn has modified the API that is used for authentication. 

The new endpoint is: **https://api.ah.nl/mobile-auth/v1/auth/token/anonymous**

If you can give me some time I will incorporate this into the library to make it available again.

**Comment by bartmachielsen** [comment]
I have just released version 0.7 which fixes the issues you are experiencing. If still issues please let me know. I will also look in implementing the Albert Heijn "bonus" endpoints.

**Comment by IpPsar01** [comment]
@bartmachielsen 
Thanks a lot for fixing this, I really appreciate it since I use it every day!!
