### ISSUE TITLE
Token ophalen: 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by densurfer** [bartmachielsen/SupermarktConnector#16]
Voor het ophalen van de token voor de Albert Heijn krijg je problremen.
Ik weet niet of dit tijdelijk is, maar bij het ophalen van de token krijg je nu het volgende 503 Service Temporarily Unavailable.
Iemand een idee voor een andere request voor de token op te halen?

**Comment by bartmachielsen** [comment]
Please check version 0.8 I have addressed this issue yesterday

**Comment by densurfer** [comment]
Thanks!
