### ISSUE TITLE
(HTTP404)

### ISSUE THREAD

**Issue by MeneerHeijpaal** [bartmachielsen/SupermarktConnector#24]
I think there's a problem with the API or Jumbo is updating their systems?
I get a 404 error on their Mobile API.

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mobileapi.jumbo.com/v15/search?offset=0&limit=1&q=Smints`

**Comment by MarkCorazon** [comment]
#25 Should fix this
