### ISSUE TITLE
Select product

### ISSUE THREAD

**Issue by PaulRill00** [bartmachielsen/SupermarktConnector#3]
Hey I have a question.
I'd like to select a product from the AH database by its barcode id.

Is this possible with your API?

**Comment by ghost** [comment]
Hey Paul.
I haven't tested if the retail barcodes that you mean are the same as the online ids. You may be able to test that with an online barcode generator/reader though.
"wi130273" (ah-scharreleieren-m-voordeel) = https://www.barcodesinc.com/generator/image.php?code=wi130273&style=197&type=C128B&width=154&height=50&xres=1&font=3
Anyway, if you just want to get product information from the AH database you can use the online ids in a simple GET request, by simply calling https://www.ah.nl/service/rest/producten/product/your_id_here/
That'll give you a JSON file with plenty of info. If you want to find out where to get those ids just browse their website and pay attention to the URL and you'll find the ids right after "product/".
I believe that you can also get all the ids (around 12.500) by just clicking here https://www.ah.nl/xmlsitemap?productTaxonomyLevelId=0 
Good luck!

**Comment by PaulRill00** [comment]
I tried using the following link:
https://www.ah.nl/service/rest/producten/product/wi130874

But that does not seem to work. I don't get any response.

**Comment by ghost** [comment]
Hi Paul.
You're right. The ids that I used for my comment were from a previous project. Apparently with new ids you need to also include the rest of the URL. Therefore the ids are no longer just "/wi+number/" but "/wi+number/product-name". I just searched for milk and this is the "complete" id: "wi200486/de-zaanse-hoeve-halfvolle-melk". Let's try with your regular web browser this link: www.ah.nl/service/rest/producten/product/wi200486/de-zaanse-hoeve-halfvolle-melk

**Comment by PaulRill00** [comment]
Problem is, I only know the id. And I am using this to get the name and price of the product...

**Comment by ghost** [comment]
You can search "wi130874" in the xml response https://www.ah.nl/xmlsitemap?productTaxonomyLevelId=0
This gives you the following product: https://www.ah.nl/producten/product/wi130874/coca-cola-regular and from there we craft its JSON https://www.ah.nl/service/rest/producten/product/wi130874/coca-cola-regular

**Comment by PaulRill00** [comment]
That would be an option. But I would loop over all the objects in the xml return?
Or just search for the string "wi130874" and then copy the rest untill I hit http?
Seems a bit weird.

**Comment by ghost** [comment]
Whichever option suits you best...

**Comment by bartmachielsen** [comment]
> Hey I have a question.
> I'd like to select a product from the AH database by its barcode id.
> 
> Is this possible with your API?

Yes since the new API releases there has been an endpoint available for getting product information based on the barcode found on the product packages.

I have updated the package to use that new release, note that you can also just install the package via pip. `pip install supermarktconnector`

```python
from supermarktconnector.jumbo import JumboConnector
connector = JumboConnector()
connector.get_product_by_barcode('8410031965902')
```
Or the same function for the AHConnector, note that the output is not normalized.
