### ISSUE TITLE
AH Api changed

### ISSUE THREAD

**Issue by duncte123** [bartmachielsen/SupermarktConnector#4]
Recently I noticed that the mobile api for AlbertHein changed causing this application to not function anymore.
From my testing it seems that the api returns a `308` http status code without body for `/rest/ah/v1/members`
I did do some digging around in the mobile app where I found these constants but have not been able to fix it yet
![image](https://user-images.githubusercontent.com/8843386/72326276-35eb2100-36af-11ea-977d-46861fb8125b.png)
In my attempts to fix the code it seems that a parameter was missing but I've not been able to figure out what the parameter is 
```json
{"errors":[{"errorCode":"GEN006","messages":[{"language":"nl","message":"Er ontbreekt een verplichte \"request parameter\""},{"language":"en","message":"Missing required request parameter"}]}]}
```

**Comment by bartmachielsen** [comment]
Yes it seems that they have released a new API version, I'm working on updating the library to make use of the new API.

**Comment by bartmachielsen** [comment]
I have updated the library to use the new AH and Jumbo API. There has been also some usability updates that you can just install the library via Pip.
`pip install supermarktconnector`

See the README for more details about the new implementation, Note that I'm still working on the documentation.
