### ISSUE TITLE
Products list does not seem to work?

### ISSUE THREAD

**Issue by daphnesmit** [bartmachielsen/SupermarktConnector#5]
Are you getting the /products api to work?
http://mobileapi.jumbo.com/v2/products?categoryId=SG9&count=10&offset=1 for example doesn't seem to work?
also without the count and offset properties. I am using x-jumbo-token header.
By id does seem to work: http://mobileapi.jumbo.com/v2/products?id=151611PAK

**Comment by bartmachielsen** [comment]
Hi Daphne, Yes the previous version (v2) is broken. If you update the URL to v9 then it will work again:
https://mobileapi.jumbo.com/v9/products?categoryId=SG9&count=10&offset=1

I'm working on updating the library. The x-jumbo-token header does not seem to have any impact anymore, I think that jumbo stopped making the prices dependant on the store location.

**Comment by daphnesmit** [comment]
awesome!

**Comment by bartmachielsen** [comment]
I have updated the library to use the new AH and Jumbo API. There has been also some usability updates that you can just install the library via Pip.
`pip install supermarktconnector`

See the README for more details about the new implementation, Note that I'm still working on the documentation.

```python
from supermarktconnector.jumbo import JumboConnector
connector = JumboConnector()
connector.search_products(query='Smint', size=10_000, page=0)
```
Note that the jumbo allows the page `size` parameter to be very large, during tested the size could be as large as 10.000 articles.
